spring:
  application:
    name: movie-recommendation

  datasource:
    hikari:
      maximum-pool-size: 4
    url: jdbc:mysql://localhost:3306/catch_mind
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect

    hibernate:
      ddl-auto: update
    show-sql: true
